services:
  wg-easy:
    environment:
     - PORT=51821
     - HOST=0.0.0.0
     - INSECURE=false
     - DISABLE_IPV6=true

    image: ghcr.io/wg-easy/wg-easy:15
    container_name: wg-easy
    networks:
      - wg
      - caddynet
    volumes:
      - ./etc:/etc/wireguard
      - /lib/modules:/lib/modules:ro
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
      # - NET_RAW # ⚠️ Uncomment if using Podman
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=1

networks:
  wg:
    driver: bridge
    name: wg
  caddynet:
    driver: bridge
    external: true
