services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    user: "1000:1000"
    ports:
      - "127.0.0.1:5678:5678"
    environment:
      - WEBHOOK_URL=http://localhost:5678/
      - GENERIC_TIMEZONE=Asia/Riyadh
      - N8N_PROTOCOL=https
    volumes:
      - ./data:/home/node/.n8n
    restart: always
    networks:
      - n8nnet
      - caddynet

networks:
  n8nnet:
    driver: bridge
    name: n8nnet 
  caddynet:
    driver: bridge
    external: true
