services:
    wg-easy:
        container_name: wg-easy
        environment:
            - LANG=en
            - WG_HOST=172.245.19.6
            - PASSWORD_HASH=$2a$12$SqyepoCQR6YW.qtf3qaLTek0OitjooAP5EEQHyogt46wg6CMLWieS
            - PORT=51821
            - WG_PORT=51820
	        - WG_DEFAULT_DNS=8.8.8.8
        volumes:
            - $PWD/wg-easy:/etc/wireguard
        ports:
            - 51820:51820/udp
            - 51821:51821/tcp
        cap_add:
            - NET_ADMIN
            - SYS_MODULE
        sysctls:
            - net.ipv4.conf.all.src_valid_mark=1
            - net.ipv4.ip_forward=1
        restart: always
        image: ghcr.io/wg-easy/wg-easy