services:
  # WireGuard VPN configuration for Gluetun container
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    networks:
      - caddynet
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 3000:3000
      - 3001:3001
    environment:
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=wireguard
      - WIREGUARD_ENDPOINT_IP=1.2.3.4
      - WIREGUARD_ENDPOINT_PORT=51820
      - WIREGUARD_PUBLIC_KEY=wAUaJMhAq3NFutLHIdF8AN0B5WG8RndfQKLPTEDHal0=
      - WIREGUARD_PRIVATE_KEY=wOEI9rqqbDwnN8/Bpp22sVz48T71vJ4fYmFWujulwUU=
      - WIREGUARD_PRESHARED_KEY=xOEI9rqqbDwnN8/Bpp22sVz48T71vJ4fYmFWujulwUU=
      - WIREGUARD_ADDRESSES=10.64.222.21/32
 
  # Firefox container using Gluetun for VPN
  firefox:
    image: lscr.io/linuxserver/firefox:latest
    container_name: firefox
    network_mode: service:gluetun
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Riyadh
      - CUSTOM_USER=admin
      - PASSWORD=password
      - TITLE=Firefox
      - START_DOCKER=true
      - FIREFOX_CLI=https://www.linuxserver.io/ #optional
    volumes:
      - firefox:/config
    shm_size: "5gb"
    restart: always

volumes:
  firefox:
    driver: local


networks:
  firefox:
    driver: bridge
    external: false
  caddynet:
    driver: bridge
    external: true